// <auto-generated />
using System;
using ErkanTatilPlani.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErkanTatilPlani.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114150956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Izmir, Alsancak",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ege bolgesi turlari",
                            Email = "info@egetur.com",
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/egetur/200",
                            Name = "Ege Tur",
                            Phone = "0232 555 1234",
                            TaxNumber = "1234567890",
                            Website = "www.egetur.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Trabzon, Meydan",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karadeniz yayla turlari",
                            Email = "info@karadenizgezileri.com",
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/karadeniz/200",
                            Name = "Karadeniz Gezileri",
                            Phone = "0462 555 5678",
                            TaxNumber = "2345678901",
                            Website = "www.karadenizgezileri.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Antalya, Konyaalti",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Akdeniz sahil turlari",
                            Email = "info@akdenizturizm.com",
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/akdeniz/200",
                            Name = "Akdeniz Turizm",
                            Phone = "0242 555 9012",
                            TaxNumber = "3456789012",
                            Website = "www.akdenizturizm.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nevsehir, Goreme",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kapadokya balon ve kultur turlari",
                            Email = "info@kapadokyabalonlari.com",
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/kapadokya/200",
                            Name = "Kapadokya Balonlari",
                            Phone = "0384 555 3456",
                            TaxNumber = "4567890123",
                            Website = "www.kapadokyabalonlari.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Istanbul, Sultanahmet",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Istanbul sehir ve bogazici turlari",
                            Email = "info@istanbulturlari.com",
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/istanbul/200",
                            Name = "Istanbul Turlari",
                            Phone = "0212 555 7890",
                            TaxNumber = "5678901234",
                            Website = "www.istanbulturlari.com"
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FlagIcon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCulture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Rtl")
                        .HasColumnType("boolean");

                    b.Property<string>("UniqueSeoCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCulture")
                        .IsUnique();

                    b.HasIndex("UniqueSeoCode")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            FlagIcon = "fi fi-tr",
                            IsActive = true,
                            IsDefault = true,
                            LanguageCulture = "tr-TR",
                            Name = "Turkce",
                            Rtl = false,
                            UniqueSeoCode = "tr"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            FlagIcon = "fi fi-us",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "en-US",
                            Name = "English",
                            Rtl = false,
                            UniqueSeoCode = "en"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            FlagIcon = "fi fi-de",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "de-DE",
                            Name = "Deutsch",
                            Rtl = false,
                            UniqueSeoCode = "de"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            FlagIcon = "fi fi-ru",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "ru-RU",
                            Name = "Русский",
                            Rtl = false,
                            UniqueSeoCode = "ru"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            FlagIcon = "fi fi-es",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "es-ES",
                            Name = "Espanol",
                            Rtl = false,
                            UniqueSeoCode = "es"
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.LocaleStringResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResourceValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "ResourceName")
                        .IsUnique();

                    b.ToTable("LocaleStringResources");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Ogle yemegi dahil",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 1500m,
                            TourId = 1,
                            VisitorId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Aile gezisi",
                            NumberOfPeople = 4,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 4800m,
                            TourId = 4,
                            VisitorId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Balon ucusu sabah erken",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 7000m,
                            TourId = 10,
                            VisitorId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "",
                            NumberOfPeople = 3,
                            StartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TotalPrice = 1350m,
                            TourId = 13,
                            VisitorId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Balikadamla dalis isteniyor",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 2200m,
                            TourId = 8,
                            VisitorId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Ozel kutlama",
                            NumberOfPeople = 5,
                            StartDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 1750m,
                            TourId = 14,
                            VisitorId = 8
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Efes antik kenti ve Meryem Ana evi gezisi",
                            Destination = "Selcuk, Izmir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/efes/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 40,
                            Name = "Efes Antik Kent Turu",
                            Price = 750m
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cesme ve Alacati sokaklarinda keyifli bir gun",
                            Destination = "Cesme, Izmir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/cesme/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 30,
                            Name = "Cesme-Alacati Turu",
                            Price = 500m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beyaz travertenler ve Hierapolis antik kenti",
                            Destination = "Pamukkale, Denizli",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/pamukkale/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 35,
                            Name = "Pamukkale Turu",
                            Price = 900m
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uzungol ve cevresindeki yaylalar",
                            Destination = "Uzungol, Trabzon",
                            DurationDays = 3,
                            ImageUrl = "https://picsum.photos/seed/uzungol/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 25,
                            Name = "Uzungol Turu",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ayder yaylasi ve sicak su kaynaklari",
                            Destination = "Ayder, Rize",
                            DurationDays = 4,
                            ImageUrl = "https://picsum.photos/seed/ayder/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 20,
                            Name = "Ayder Yaylasi Turu",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sumela Manastiri ve Trabzon gezisi",
                            Destination = "Macka, Trabzon",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/sumela/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 30,
                            Name = "Sumela Manastiri",
                            Price = 800m
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kemer koylarinda tekne turu",
                            Destination = "Kemer, Antalya",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/kemer/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 50,
                            Name = "Kemer Tekne Turu",
                            Price = 600m
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Batan sehir Kekova ve Kas",
                            Destination = "Kas, Antalya",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/kas/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 25,
                            Name = "Kas-Kekova Turu",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Olimpos antik kenti ve Yanaras alevi",
                            Destination = "Olimpos, Antalya",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/olimpos/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 30,
                            Name = "Olimpos-Yanaras Turu",
                            Price = 850m
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peri bacalari uzerinde balon deneyimi",
                            Destination = "Goreme, Nevsehir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/balon/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 16,
                            Name = "Kapadokya Balon Turu",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeralti sehirleri ve vadiler",
                            Destination = "Kapadokya, Nevsehir",
                            DurationDays = 3,
                            ImageUrl = "https://picsum.photos/seed/vadiler/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 30,
                            Name = "Kapadokya Kultur Turu",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kapadokya vadilerinde ATV macerasi",
                            Destination = "Goreme, Nevsehir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/atv/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 20,
                            Name = "ATV Safari",
                            Price = 700m
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sultanahmet, Ayasofya, Topkapi",
                            Destination = "Sultanahmet, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/sultanahmet/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 40,
                            Name = "Tarihi Yarimada Turu",
                            Price = 450m
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Istanbul Bogazinda tekne gezisi",
                            Destination = "Bogaz, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/bogaz/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 60,
                            Name = "Bogaz Turu",
                            Price = 350m
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Buyukada ve Heybeliada gezisi",
                            Destination = "Adalar, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/adalar/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 45,
                            Name = "Prensesler Adalari",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@erkantatilplani.com",
                            FirstName = "Sistem",
                            IdentityNumber = "11111111111",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0532 111 1111",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@erkantatilplani.com",
                            FirstName = "Personel",
                            IdentityNumber = "22222222222",
                            IsActive = true,
                            LastName = "Kullanici",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0533 222 2222",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmet@egetur.com",
                            FirstName = "Ahmet",
                            IdentityNumber = "33333333333",
                            IsActive = true,
                            LastName = "Yilmaz",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0534 333 3333",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehmet@karadenizgezileri.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "44444444444",
                            IsActive = true,
                            LastName = "Kaya",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0535 444 4444",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatma@akdenizturizm.com",
                            FirstName = "Fatma",
                            IdentityNumber = "55555555555",
                            IsActive = true,
                            LastName = "Demir",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0536 555 5555",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali@kapadokyabalonlari.com",
                            FirstName = "Ali",
                            IdentityNumber = "66666666666",
                            IsActive = true,
                            LastName = "Celik",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0537 666 6666",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayse@istanbulturlari.com",
                            FirstName = "Ayse",
                            IdentityNumber = "77777777777",
                            IsActive = true,
                            LastName = "Ozturk",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0538 777 7777",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zeynep@gmail.com",
                            FirstName = "Zeynep",
                            IdentityNumber = "88888888888",
                            IsActive = true,
                            LastName = "Arslan",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0539 888 8888",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mustafa@gmail.com",
                            FirstName = "Mustafa",
                            IdentityNumber = "99999999999",
                            IsActive = true,
                            LastName = "Sahin",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0530 999 9999",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elif@gmail.com",
                            FirstName = "Elif",
                            IdentityNumber = "10101010101",
                            IsActive = true,
                            LastName = "Yildiz",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0531 000 0000",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emre@gmail.com",
                            FirstName = "Emre",
                            IdentityNumber = "12121212121",
                            IsActive = true,
                            LastName = "Koc",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0541 111 1111",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "selin@gmail.com",
                            FirstName = "Selin",
                            IdentityNumber = "13131313131",
                            IsActive = true,
                            LastName = "Aydin",
                            PasswordHash = "AQAAAAIAAYagAAAAELbJmz5DIWnN7p8HA8VQl8dZl5qQBqCmHr5gw0wEj7FdhFfP3g==",
                            Phone = "0542 222 2222",
                            UserTypeId = 0
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.LocaleStringResource", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Language", "Language")
                        .WithMany("LocaleStringResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Tour", "Tour")
                        .WithMany("Reservations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany("Reservations")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Company", "Company")
                        .WithMany("Tours")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Company", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Language", b =>
                {
                    b.Navigation("LocaleStringResources");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
