// <auto-generated />
using System;
using ErkanTatilPlani.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErkanTatilPlani.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128173507_AddVisitorProfileFields")]
    partial class AddVisitorProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicationNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractFileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SocialLinks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Izmir, Alsancak Mah. Kordon Cad. No:123",
                            ApplicationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicationNotes = "",
                            City = "Izmir",
                            ContractFileUrl = "",
                            CoverImageUrl = "https://picsum.photos/seed/egetur-cover/1200/400",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ege bolgesi turlari konusunda uzman seyahat acentasi. 15 yillik deneyimimizle Efes, Pamukkale, Cesme ve daha fazlasini kesfetmenizi sagliyoruz.",
                            Email = "info@egetur.com",
                            FoundedYear = 2010,
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/egetur/200",
                            MetaDescription = "Efes, Pamukkale, Cesme ve tum Ege turlarinda uzman acenta. Gunubirlik ve konaklamali turlar.",
                            MetaTitle = "Ege Tur - Izmir Cikisli Ege Turlari",
                            Name = "Ege Tur",
                            Phone = "0232 555 1234",
                            RejectionReason = "",
                            ReviewNotes = "",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = 1,
                            Slug = "ege-tur",
                            SocialLinks = "",
                            StatusId = 1,
                            Tagline = "Ege'nin Guzelliklerini Kesfedin",
                            TaxNumber = "1234567890",
                            Website = "www.egetur.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Trabzon, Meydan Mah. Ataturk Cad. No:45",
                            ApplicationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicationNotes = "",
                            City = "Trabzon",
                            ContractFileUrl = "",
                            CoverImageUrl = "https://picsum.photos/seed/karadeniz-cover/1200/400",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karadeniz'in essiz dogasini ve yaylalarini profesyonel rehberler esliginde kesfetmenizi saglayan tur firmasi. Uzungol, Ayder ve daha fazlasi.",
                            Email = "info@karadenizgezileri.com",
                            FoundedYear = 2015,
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/karadeniz/200",
                            MetaDescription = "Uzungol, Ayder, Sumela ve tum Karadeniz yaylalarini kesfedin. Dogayla ic ice tatil firsatlari.",
                            MetaTitle = "Karadeniz Gezileri - Yayla ve Doga Turlari",
                            Name = "Karadeniz Gezileri",
                            Phone = "0462 555 5678",
                            RejectionReason = "",
                            ReviewNotes = "",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = 1,
                            Slug = "karadeniz-gezileri",
                            SocialLinks = "",
                            StatusId = 1,
                            Tagline = "Yesil Cennetin Kapisi",
                            TaxNumber = "2345678901",
                            Website = "www.karadenizgezileri.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Antalya, Konyaalti Mah. Liman Cad. No:78",
                            ApplicationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicationNotes = "",
                            City = "Antalya",
                            ContractFileUrl = "",
                            CoverImageUrl = "https://picsum.photos/seed/akdeniz-cover/1200/400",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Turkiye'nin en guzel sahillerinde unutulmaz deneyimler. Tekne turlari, dalıs aktiviteleri ve kultur gezileri duzenliyoruz.",
                            Email = "info@akdenizturizm.com",
                            FoundedYear = 2008,
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/akdeniz/200",
                            MetaDescription = "Kemer, Kas, Kekova tekne turlari. Akdeniz'in en guzel koylarini ve antik kentleri kesfedin.",
                            MetaTitle = "Akdeniz Turizm - Antalya Tekne ve Kultur Turlari",
                            Name = "Akdeniz Turizm",
                            Phone = "0242 555 9012",
                            RejectionReason = "",
                            ReviewNotes = "",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = 1,
                            Slug = "akdeniz-turizm",
                            SocialLinks = "",
                            StatusId = 1,
                            Tagline = "Akdeniz'in Mavisiyle Tanisin",
                            TaxNumber = "3456789012",
                            Website = "www.akdenizturizm.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nevsehir, Goreme Kasabasi Merkez No:12",
                            ApplicationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicationNotes = "",
                            City = "Nevsehir",
                            ContractFileUrl = "",
                            CoverImageUrl = "https://picsum.photos/seed/kapadokya-cover/1200/400",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kapadokya'nin buleyuci peri bacalari uzerinde balon deneyimi ve kultur turlari. Yeralti sehirleri, vadiler ve daha fazlasi.",
                            Email = "info@kapadokyabalonlari.com",
                            FoundedYear = 2012,
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/kapadokya/200",
                            MetaDescription = "Kapadokya balon turu, yeralti sehirleri, ATV safari. Peri bacalari uzerinde unutulmaz deneyim.",
                            MetaTitle = "Kapadokya Balonlari - Sicak Hava Balonu ve Tur",
                            Name = "Kapadokya Balonlari",
                            Phone = "0384 555 3456",
                            RejectionReason = "",
                            ReviewNotes = "",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = 1,
                            Slug = "kapadokya-balonlari",
                            SocialLinks = "",
                            StatusId = 1,
                            Tagline = "Gokyuzunden Kapadokya",
                            TaxNumber = "4567890123",
                            Website = "www.kapadokyabalonlari.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Istanbul, Sultanahmet Mah. Divanyolu Cad. No:56",
                            ApplicationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApplicationNotes = "",
                            City = "Istanbul",
                            ContractFileUrl = "",
                            CoverImageUrl = "https://picsum.photos/seed/istanbul-cover/1200/400",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dunyanin en etkileyici sehrinde tarihi ve kulturel turlarin adresi. Sultanahmet, Bogaz turlari ve ozel organizasyonlar.",
                            Email = "info@istanbulturlari.com",
                            FoundedYear = 2005,
                            IsActive = true,
                            LogoUrl = "https://picsum.photos/seed/istanbul/200",
                            MetaDescription = "Sultanahmet, Ayasofya, Topkapi Sarayi, Bogaz turu. Istanbul'un tum guzelliklerini kesfedin.",
                            MetaTitle = "Istanbul Turlari - Tarihi Yarimada ve Bogaz Turu",
                            Name = "Istanbul Turlari",
                            Phone = "0212 555 7890",
                            RejectionReason = "",
                            ReviewNotes = "",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = 1,
                            Slug = "istanbul-turlari",
                            SocialLinks = "",
                            StatusId = 1,
                            Tagline = "Iki Kitanin Kesisim Noktasi",
                            TaxNumber = "5678901234",
                            Website = "www.istanbulturlari.com"
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FlagIcon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCulture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Rtl")
                        .HasColumnType("boolean");

                    b.Property<string>("UniqueSeoCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCulture")
                        .IsUnique();

                    b.HasIndex("UniqueSeoCode")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            FlagIcon = "fi fi-tr",
                            IsActive = true,
                            IsDefault = true,
                            LanguageCulture = "tr-TR",
                            Name = "Turkce",
                            Rtl = false,
                            UniqueSeoCode = "tr"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            FlagIcon = "fi fi-us",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "en-US",
                            Name = "English",
                            Rtl = false,
                            UniqueSeoCode = "en"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            FlagIcon = "fi fi-de",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "de-DE",
                            Name = "Deutsch",
                            Rtl = false,
                            UniqueSeoCode = "de"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            FlagIcon = "fi fi-ru",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "ru-RU",
                            Name = "Русский",
                            Rtl = false,
                            UniqueSeoCode = "ru"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            FlagIcon = "fi fi-es",
                            IsActive = true,
                            IsDefault = false,
                            LanguageCulture = "es-ES",
                            Name = "Espanol",
                            Rtl = false,
                            UniqueSeoCode = "es"
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.LocaleStringResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResourceValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId", "ResourceName")
                        .IsUnique();

                    b.ToTable("LocaleStringResources");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Ogle yemegi dahil",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 1500m,
                            TourId = 1,
                            VisitorId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Aile gezisi",
                            NumberOfPeople = 4,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 4800m,
                            TourId = 4,
                            VisitorId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Balon ucusu sabah erken",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 7000m,
                            TourId = 10,
                            VisitorId = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "",
                            NumberOfPeople = 3,
                            StartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TotalPrice = 1350m,
                            TourId = 13,
                            VisitorId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Balikadamla dalis isteniyor",
                            NumberOfPeople = 2,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 2200m,
                            TourId = 8,
                            VisitorId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Ozel kutlama",
                            NumberOfPeople = 5,
                            StartDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 1750m,
                            TourId = 14,
                            VisitorId = 8
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewHelpful", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("VisitorId");

                    b.HasIndex("ReviewId", "VisitorId")
                        .IsUnique();

                    b.ToTable("ReviewHelpfuls");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFromCompany")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModeratedById")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentReplyId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedById");

                    b.HasIndex("ParentReplyId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("VisitorId");

                    b.ToTable("ReviewReplies");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReplyId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("VisitorId");

                    b.ToTable("ReviewReports");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 0m,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Efes antik kenti ve Meryem Ana evi gezisi",
                            Destination = "Selcuk, Izmir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/efes/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 40,
                            Name = "Efes Antik Kent Turu",
                            Price = 750m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 0m,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cesme ve Alacati sokaklarinda keyifli bir gun",
                            Destination = "Cesme, Izmir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/cesme/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 30,
                            Name = "Cesme-Alacati Turu",
                            Price = 500m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 0m,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beyaz travertenler ve Hierapolis antik kenti",
                            Destination = "Pamukkale, Denizli",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/pamukkale/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 35,
                            Name = "Pamukkale Turu",
                            Price = 900m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 0m,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uzungol ve cevresindeki yaylalar",
                            Destination = "Uzungol, Trabzon",
                            DurationDays = 3,
                            ImageUrl = "https://picsum.photos/seed/uzungol/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 25,
                            Name = "Uzungol Turu",
                            Price = 1200m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 0m,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ayder yaylasi ve sicak su kaynaklari",
                            Destination = "Ayder, Rize",
                            DurationDays = 4,
                            ImageUrl = "https://picsum.photos/seed/ayder/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 20,
                            Name = "Ayder Yaylasi Turu",
                            Price = 1400m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 0m,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sumela Manastiri ve Trabzon gezisi",
                            Destination = "Macka, Trabzon",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/sumela/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 30,
                            Name = "Sumela Manastiri",
                            Price = 800m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 0m,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kemer koylarinda tekne turu",
                            Destination = "Kemer, Antalya",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/kemer/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 50,
                            Name = "Kemer Tekne Turu",
                            Price = 600m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 0m,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Batan sehir Kekova ve Kas",
                            Destination = "Kas, Antalya",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/kas/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 25,
                            Name = "Kas-Kekova Turu",
                            Price = 1100m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 0m,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Olimpos antik kenti ve Yanaras alevi",
                            Destination = "Olimpos, Antalya",
                            DurationDays = 2,
                            ImageUrl = "https://picsum.photos/seed/olimpos/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 30,
                            Name = "Olimpos-Yanaras Turu",
                            Price = 850m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 0m,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peri bacalari uzerinde balon deneyimi",
                            Destination = "Goreme, Nevsehir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/balon/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 16,
                            Name = "Kapadokya Balon Turu",
                            Price = 3500m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 0m,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeralti sehirleri ve vadiler",
                            Destination = "Kapadokya, Nevsehir",
                            DurationDays = 3,
                            ImageUrl = "https://picsum.photos/seed/vadiler/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 30,
                            Name = "Kapadokya Kultur Turu",
                            Price = 1800m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 0m,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kapadokya vadilerinde ATV macerasi",
                            Destination = "Goreme, Nevsehir",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/atv/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 20,
                            Name = "ATV Safari",
                            Price = 700m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 0m,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sultanahmet, Ayasofya, Topkapi",
                            Destination = "Sultanahmet, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/sultanahmet/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 40,
                            Name = "Tarihi Yarimada Turu",
                            Price = 450m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 0m,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Istanbul Bogazinda tekne gezisi",
                            Destination = "Bogaz, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/bogaz/800/600",
                            IsActive = true,
                            IsFeatured = true,
                            MaxCapacity = 60,
                            Name = "Bogaz Turu",
                            Price = 350m,
                            ReviewCount = 0
                        },
                        new
                        {
                            Id = 15,
                            AverageRating = 0m,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Buyukada ve Heybeliada gezisi",
                            Destination = "Adalar, Istanbul",
                            DurationDays = 1,
                            ImageUrl = "https://picsum.photos/seed/adalar/800/600",
                            IsActive = true,
                            IsFeatured = false,
                            MaxCapacity = 45,
                            Name = "Prensesler Adalari",
                            Price = 400m,
                            ReviewCount = 0
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.TourReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuideRating")
                        .HasColumnType("integer");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocationRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModeratedById")
                        .HasColumnType("integer");

                    b.Property<string>("ModerationNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotHelpfulCount")
                        .HasColumnType("integer");

                    b.Property<int?>("OrganizationRating")
                        .HasColumnType("integer");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceRating")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.Property<int>("TravelTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer");

                    b.Property<bool>("WouldRecommend")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedById");

                    b.HasIndex("ReservationId");

                    b.HasIndex("VisitorId");

                    b.HasIndex("TourId", "VisitorId")
                        .IsUnique();

                    b.ToTable("TourReviews");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@erkantatilplani.com",
                            FirstName = "Sistem",
                            IdentityNumber = "11111111111",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0532 111 1111",
                            PreferredLanguage = "tr",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@erkantatilplani.com",
                            FirstName = "Personel",
                            IdentityNumber = "22222222222",
                            IsActive = true,
                            LastName = "Kullanici",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0533 222 2222",
                            PreferredLanguage = "tr",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmet@egetur.com",
                            FirstName = "Ahmet",
                            IdentityNumber = "33333333333",
                            IsActive = true,
                            LastName = "Yilmaz",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0534 333 3333",
                            PreferredLanguage = "tr",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehmet@karadenizgezileri.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "44444444444",
                            IsActive = true,
                            LastName = "Kaya",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0535 444 4444",
                            PreferredLanguage = "tr",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatma@akdenizturizm.com",
                            FirstName = "Fatma",
                            IdentityNumber = "55555555555",
                            IsActive = true,
                            LastName = "Demir",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0536 555 5555",
                            PreferredLanguage = "tr",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali@kapadokyabalonlari.com",
                            FirstName = "Ali",
                            IdentityNumber = "66666666666",
                            IsActive = true,
                            LastName = "Celik",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0537 666 6666",
                            PreferredLanguage = "tr",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayse@istanbulturlari.com",
                            FirstName = "Ayse",
                            IdentityNumber = "77777777777",
                            IsActive = true,
                            LastName = "Ozturk",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0538 777 7777",
                            PreferredLanguage = "tr",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zeynep@gmail.com",
                            FirstName = "Zeynep",
                            IdentityNumber = "88888888888",
                            IsActive = true,
                            LastName = "Arslan",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0539 888 8888",
                            PreferredLanguage = "tr",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mustafa@gmail.com",
                            FirstName = "Mustafa",
                            IdentityNumber = "99999999999",
                            IsActive = true,
                            LastName = "Sahin",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0530 999 9999",
                            PreferredLanguage = "tr",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elif@gmail.com",
                            FirstName = "Elif",
                            IdentityNumber = "10101010101",
                            IsActive = true,
                            LastName = "Yildiz",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0531 000 0000",
                            PreferredLanguage = "tr",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emre@gmail.com",
                            FirstName = "Emre",
                            IdentityNumber = "12121212121",
                            IsActive = true,
                            LastName = "Koc",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0541 111 1111",
                            PreferredLanguage = "tr",
                            UserTypeId = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "selin@gmail.com",
                            FirstName = "Selin",
                            IdentityNumber = "13131313131",
                            IsActive = true,
                            LastName = "Aydin",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "0542 222 2222",
                            PreferredLanguage = "tr",
                            UserTypeId = 0
                        });
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Company", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.LocaleStringResource", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Language", "Language")
                        .WithMany("LocaleStringResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Reservation", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Tour", "Tour")
                        .WithMany("Reservations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany("Reservations")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewHelpful", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.TourReview", "Review")
                        .WithMany("HelpfulVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany("HelpfulVotes")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewImage", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.TourReview", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewReply", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "ModeratedBy")
                        .WithMany()
                        .HasForeignKey("ModeratedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErkanTatilPlani.Core.Entities.ReviewReply", "ParentReply")
                        .WithMany("ChildReplies")
                        .HasForeignKey("ParentReplyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ErkanTatilPlani.Core.Entities.TourReview", "Review")
                        .WithMany("Replies")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany("ReviewReplies")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeratedBy");

                    b.Navigation("ParentReply");

                    b.Navigation("Review");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewReport", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.ReviewReply", "Reply")
                        .WithMany()
                        .HasForeignKey("ReplyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ErkanTatilPlani.Core.Entities.TourReview", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reply");

                    b.Navigation("Review");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Company", "Company")
                        .WithMany("Tours")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.TourReview", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "ModeratedBy")
                        .WithMany()
                        .HasForeignKey("ModeratedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErkanTatilPlani.Core.Entities.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ErkanTatilPlani.Core.Entities.Tour", "Tour")
                        .WithMany("Reviews")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErkanTatilPlani.Core.Entities.Visitor", "Visitor")
                        .WithMany("Reviews")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeratedBy");

                    b.Navigation("Reservation");

                    b.Navigation("Tour");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.HasOne("ErkanTatilPlani.Core.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Company", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Language", b =>
                {
                    b.Navigation("LocaleStringResources");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.ReviewReply", b =>
                {
                    b.Navigation("ChildReplies");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Tour", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.TourReview", b =>
                {
                    b.Navigation("HelpfulVotes");

                    b.Navigation("Images");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ErkanTatilPlani.Core.Entities.Visitor", b =>
                {
                    b.Navigation("HelpfulVotes");

                    b.Navigation("Reservations");

                    b.Navigation("ReviewReplies");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
