using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ErkanTatilPlani.Data.Migrations
{
    /// <inheritdoc />
    public partial class RenameBrandToTours : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "EmailAccounts",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "FromEmail", "FromName", "SmtpUsername" },
                values: new object[] { "noreply@tours.corplynk.com", "Tours", "noreply@tours.corplynk.com" });

            migrationBuilder.UpdateData(
                table: "EmailAccounts",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "FromEmail", "FromName", "SmtpUsername" },
                values: new object[] { "reservations@tours.corplynk.com", "Tours - Rezervasyonlar", "reservations@tours.corplynk.com" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Sifre Sifirlama</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Sifrenizi sifirlamak icin asagidaki butona tiklayin. Eger bu istegi siz yapmadiysiniz, bu emaili gormezden gelebilirsiniz.</p>\r\n                <p style='text-align: center;'><a href='{resetUrl}' class='btn'>Sifremi Sifirla</a></p>\r\n                <p style='color: #6c757d; font-size: 14px;'>Bu link 1 saat icinde gecerliligini yitirecektir.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Sifre Sifirlama - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Password Reset</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Click the button below to reset your password. If you did not make this request, you can ignore this email.</p>\r\n                <p style='text-align: center;'><a href='{resetUrl}' class='btn'>Reset My Password</a></p>\r\n                <p style='color: #6c757d; font-size: 14px;'>This link will expire in 1 hour.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Password Reset - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Email Dogrulama</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Hesabinizi aktif etmek ve tum ozelliklere erisebilmek icin email adresinizi dogrulayin.</p>\r\n                <p style='text-align: center;'><a href='{verifyUrl}' class='btn'>Email Adresimi Dogrula</a></p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Email Dogrulama - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Email Verification</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Verify your email address to activate your account and access all features.</p>\r\n                <p style='text-align: center;'><a href='{verifyUrl}' class='btn'>Verify My Email</a></p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Email Verification - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Onaylandi!</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Rezervasyonunuz basariyla onaylandi. Asagida rezervasyon detaylarinizi bulabilirsiniz.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Bizi tercih ettiginiz icin tesekkur ederiz. Iyi tatiller dileriz!</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Onaylandi - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation is Confirmed!</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Your reservation has been confirmed successfully. Below you can find your reservation details.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Thank you for choosing us. Have a great trip!</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation is Confirmed - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Iptal Edildi</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Rezervasyonunuz iptal edilmistir.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Sorulariniz icin bizimle iletisime gecebilirsiniz.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Iptal Edildi - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation has been Cancelled</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Your reservation has been cancelled.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>For any questions, please contact us.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation has been Cancelled - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Reddedildi</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Uzulerek bildirmek isteriz ki rezervasyonunuz reddedilmistir.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                    <div class='details-row'><span><strong>Sebep:</strong></span><span>{rejectionReason}</span></div>\r\n                </div>\r\n                <p>Sorulariniz icin bizimle iletisime gecebilirsiniz.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Reddedildi - Tours" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation has been Rejected</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>We regret to inform you that your reservation has been rejected.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                    <div class='details-row'><span><strong>Reason:</strong></span><span>{rejectionReason}</span></div>\r\n                </div>\r\n                <p>For any questions, please contact us.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Tours tarafindan otomatik olarak gonderilmistir.</p>\n            <p>&copy; 2026 Tours. Tum haklari saklidir.</p>\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation has been Rejected - Tours" });

            migrationBuilder.UpdateData(
                table: "Visitors",
                keyColumn: "Id",
                keyValue: 1,
                column: "Email",
                value: "admin@tours.corplynk.com");

            migrationBuilder.UpdateData(
                table: "Visitors",
                keyColumn: "Id",
                keyValue: 2,
                column: "Email",
                value: "staff@tours.corplynk.com");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "EmailAccounts",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "FromEmail", "FromName", "SmtpUsername" },
                values: new object[] { "noreply@erkantatilplani.com", "Erkan Tatil Plani", "noreply@erkantatilplani.com" });

            migrationBuilder.UpdateData(
                table: "EmailAccounts",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "FromEmail", "FromName", "SmtpUsername" },
                values: new object[] { "reservations@erkantatilplani.com", "Erkan Tatil Plani - Rezervasyonlar", "reservations@erkantatilplani.com" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 1,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Sifre Sifirlama</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Sifrenizi sifirlamak icin asagidaki butona tiklayin. Eger bu istegi siz yapmadiysiniz, bu emaili gormezden gelebilirsiniz.</p>\r\n                <p style='text-align: center;'><a href='{resetUrl}' class='btn'>Sifremi Sifirla</a></p>\r\n                <p style='color: #6c757d; font-size: 14px;'>Bu link 1 saat icinde gecerliligini yitirecektir.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Sifre Sifirlama - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 2,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Password Reset</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Click the button below to reset your password. If you did not make this request, you can ignore this email.</p>\r\n                <p style='text-align: center;'><a href='{resetUrl}' class='btn'>Reset My Password</a></p>\r\n                <p style='color: #6c757d; font-size: 14px;'>This link will expire in 1 hour.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Password Reset - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 3,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Email Dogrulama</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Hesabinizi aktif etmek ve tum ozelliklere erisebilmek icin email adresinizi dogrulayin.</p>\r\n                <p style='text-align: center;'><a href='{verifyUrl}' class='btn'>Email Adresimi Dogrula</a></p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Email Dogrulama - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 4,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Email Verification</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Verify your email address to activate your account and access all features.</p>\r\n                <p style='text-align: center;'><a href='{verifyUrl}' class='btn'>Verify My Email</a></p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Email Verification - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 5,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Onaylandi!</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Rezervasyonunuz basariyla onaylandi. Asagida rezervasyon detaylarinizi bulabilirsiniz.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Bizi tercih ettiginiz icin tesekkur ederiz. Iyi tatiller dileriz!</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Onaylandi - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 6,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation is Confirmed!</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Your reservation has been confirmed successfully. Below you can find your reservation details.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Thank you for choosing us. Have a great trip!</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation is Confirmed - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 7,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Iptal Edildi</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Rezervasyonunuz iptal edilmistir.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>Sorulariniz icin bizimle iletisime gecebilirsiniz.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Iptal Edildi - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 8,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation has been Cancelled</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>Your reservation has been cancelled.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                </div>\r\n                <p>For any questions, please contact us.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation has been Cancelled - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 9,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Rezervasyonunuz Reddedildi</h1></div>\r\n            <div class='content'>\r\n                <p>Merhaba {customerName},</p>\r\n                <p>Uzulerek bildirmek isteriz ki rezervasyonunuz reddedilmistir.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tur:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Firma:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destinasyon:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Tarih:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Kisi Sayisi:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Toplam:</strong></span><span>{totalPrice} TL</span></div>\r\n                    <div class='details-row'><span><strong>Sebep:</strong></span><span>{rejectionReason}</span></div>\r\n                </div>\r\n                <p>Sorulariniz icin bizimle iletisime gecebilirsiniz.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Rezervasyonunuz Reddedildi - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "EmailTemplateTranslations",
                keyColumn: "Id",
                keyValue: 10,
                columns: new[] { "Body", "Subject" },
                values: new object[] { "<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset='utf-8'>\r\n    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\r\n    <style>\r\n        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }\r\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; }\r\n        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; }\r\n        .header h1 { color: #ffffff; margin: 0; font-size: 24px; }\r\n        .content { padding: 40px 30px; }\r\n        .btn { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #ffffff; padding: 14px 30px; text-decoration: none; border-radius: 5px; font-weight: 600; margin: 20px 0; }\r\n        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #6c757d; }\r\n        .details { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\r\n        .details-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e9ecef; }\r\n        .details-row:last-child { border-bottom: none; }\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class='container'>\r\n        \r\n            <div class='header'><h1>Your Reservation has been Rejected</h1></div>\r\n            <div class='content'>\r\n                <p>Hello {customerName},</p>\r\n                <p>We regret to inform you that your reservation has been rejected.</p>\r\n                <div class='details'>\r\n                    <div class='details-row'><span><strong>Tour:</strong></span><span>{tourName}</span></div>\r\n                    <div class='details-row'><span><strong>Company:</strong></span><span>{companyName}</span></div>\r\n                    <div class='details-row'><span><strong>Destination:</strong></span><span>{destination}</span></div>\r\n                    <div class='details-row'><span><strong>Date:</strong></span><span>{startDate} - {endDate}</span></div>\r\n                    <div class='details-row'><span><strong>Number of People:</strong></span><span>{numberOfPeople}</span></div>\r\n                    <div class='details-row'><span><strong>Total:</strong></span><span>{totalPrice} TL</span></div>\r\n                    <div class='details-row'><span><strong>Reason:</strong></span><span>{rejectionReason}</span></div>\r\n                </div>\r\n                <p>For any questions, please contact us.</p>\r\n            </div>\r\n        <div class='footer'>\r\n            <p>Bu email Erkan Tatil Plani tarafindan otomatik olarak gonderilmistir.</p>\r\n            <p>&copy; 2026 Erkan Tatil Plani. Tum haklari saklidir.</p>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>", "Your Reservation has been Rejected - Erkan Tatil Plani" });

            migrationBuilder.UpdateData(
                table: "Visitors",
                keyColumn: "Id",
                keyValue: 1,
                column: "Email",
                value: "admin@erkantatilplani.com");

            migrationBuilder.UpdateData(
                table: "Visitors",
                keyColumn: "Id",
                keyValue: 2,
                column: "Email",
                value: "staff@erkantatilplani.com");
        }
    }
}
